### ISSUE TITLE
Feature Request : separate folders for each list subscription

### ISSUE THREAD

**Issue by likeitneverwentaway** [mancuniancol/script.subscription.quasar.trakt#1]
Basically if we can have separate folders for different lists then we could more easily set up library playlist, one for your favorite movies, one for most popular...

Thanks!

**Comment by mancuniancol** [comment]
The script separates the same way that kodi does.  Movies and TV Shows

**Comment by mancuniancol** [comment]
Anyway, Quasar is having trakt integration. Then, I will stop any development of this script. 
You can ask to Quasar developpers for that feature.
