### ISSUE TITLE
wrong .strm url structure

### ISSUE THREAD

**Issue by vdutch** [mancuniancol/script.subscription.quasar.trakt#3]
There's an error in the .strm url structure when scraping movies (on tvshows the structure is correct)
Example: plugin://plugin.video.quasar/movie/76203/links/links
should be: plugin://plugin.video.quasar/movie/76203/links

This causes a navigation error when trying to open a link from the library

**Comment by mancuniancol** [comment]
Which mctools version do you have? That was fixed with version 1.3.6

**Comment by vdutch** [comment]
1.3.5...  is there any repository i can install so i can mantain mctools updated?

**Comment by mancuniancol** [comment]
Not yet. I hope soon. 
https://github.com/mancuniancol/script.module.mctools/archive/v1.3.6.zip

**Comment by vdutch** [comment]
Thanks ;)
