### ISSUE TITLE
plugin doesn't seem to work on xbian (latest)

### ISSUE THREAD

**Issue by eggsterino** [mancuniancol/script.subscription.quasar.trakt#4]
No matter if I try to subscribe the watchlist or other lists - nothing seems to happen. I've checked the user name and the url and it is OK. Here is the log:

01:45:05 1057.003052 T:1497813936  NOTICE: [Quasar TRAKT list subscription] http://trakt.tv/users/<my-user-name>/lists/
01:45:10 1061.786987 T:1497813936  NOTICE: [Quasar TRAKT list subscription] http://trakt.tv
01:46:05 1117.165283 T:1497813936  NOTICE: Previous line repeats 1 times.

Thanks

**Comment by mancuniancol** [comment]
This script is deprecated, because Quasar gives Trakt support natively

**Comment by eggsterino** [comment]
From what quasar  version? I don't see any trakt support in quasar.

**Comment by mancuniancol** [comment]
Please, check this link. https://github.com/scakemyer/plugin.video.quasar/issues/31
